import CoreMedia
import Foundation

/// A time-range in the timeline where a zoom is active. Keyframes are *relative to region start*.
struct ZoomRegion: Codable, Hashable, Identifiable {
    var id: UUID
    var start: CMTime
    var end: CMTime
    var keyframes: [ZoomKeyframe]
    var timingFunction: TimingFunction
    var isAutoGenerated: Bool

    var duration: CMTime { CMTimeSubtract(end, start) }
}
