import CoreMedia
import SwiftUI

/// SwiftUI shell hosting the AppKit timeline (for dense-drawing perf) plus a ruler, playhead, and
/// zoom region chips rendered in SwiftUI on top of the scroll content.
///
/// MVP: SwiftUI-only. The NSView path lives in `TimelineView.swift` for the dense-drawing upgrade
/// in a follow-up pass; for the critical path this scrollable SwiftUI strip does the job.
struct TimelinePanel: View {
    @ObservedObject var vm: EditorViewModel

    var body: some View {
        GeometryReader { geo in
            VStack(spacing: 0) {
                header
                TimelineStripView(vm: vm, width: geo.size.width)
            }
        }
    }

    private var header: some View {
        HStack(spacing: Spacing.m) {
            Text("Timeline").font(Typography.small.weight(.semibold)).foregroundStyle(.secondary)
            Spacer()
            HStack(spacing: Spacing.s) {
                Image(systemName: Icons.zoomOut).foregroundStyle(.secondary).font(.system(size: 10))
                Slider(value: Binding(
                    get: { vm.model.pixelsPerSecond },
                    set: { vm.model.pixelsPerSecond = $0 }
                ), in: 24...320).frame(width: 160)
                Image(systemName: Icons.zoomIn).foregroundStyle(.secondary).font(.system(size: 10))
            }
        }
        .padding(.horizontal, Spacing.l)
        .padding(.top, Spacing.s)
        .frame(height: 32)
    }
}

private struct TimelineStripView: View {
    @ObservedObject var vm: EditorViewModel
    let width: CGFloat

    @State private var isScrubbing = false

    var body: some View {
        let dur = vm.model.project.sourceDuration.secondsOrZero
        let pps = vm.model.pixelsPerSecond
        let totalWidth = max(width, CGFloat(dur) * pps)

        ScrollView(.horizontal, showsIndicators: false) {
            ZStack(alignment: .topLeading) {
                // Ruler
                RulerCanvas(duration: dur, pixelsPerSecond: pps)
                    .frame(width: totalWidth, height: 20)
                    .offset(y: 0)

                // Zoom regions
                ForEach(vm.model.project.zoomTrack, id: \.id) { region in
                    let x = CGFloat(region.start.secondsOrZero) * pps
                    let w = CGFloat(region.duration.secondsOrZero) * pps
                    RoundedRectangle(cornerRadius: Radius.s)
                        .fill(LinearGradient(colors: [Palette.accent.opacity(0.7), .indigo.opacity(0.5)],
                                             startPoint: .leading, endPoint: .trailing))
                        .overlay(
                            HStack {
                                Image(systemName: Icons.zoomIn).foregroundStyle(.white.opacity(0.9))
                                    .font(.system(size: 10))
                                Text(region.isAutoGenerated ? "Auto" : "Zoom")
                                    .font(Typography.small.weight(.semibold))
                                    .foregroundStyle(.white.opacity(0.9))
                            }.padding(.leading, 6)
                            , alignment: .leading
                        )
                        .frame(width: w, height: 34)
                        .offset(x: x, y: 28)
                }

                // Playhead
                let t = vm.renderer.currentTime.secondsOrZero
                let px = CGFloat(t) * pps
                Rectangle()
                    .fill(Color.red)
                    .frame(width: 1.5, height: 160)
                    .offset(x: px, y: 0)
            }
            .frame(width: totalWidth, height: 160)
        }
        .contentShape(Rectangle())
        .gesture(
            DragGesture(minimumDistance: 0)
                .onChanged { value in
                    isScrubbing = true
                    let x = max(0, value.location.x)
                    let s = Double(x / max(1, vm.model.pixelsPerSecond)).clamped(0, dur)
                    vm.seek(to: CMTime(seconds: s, preferredTimescale: 1_000_000_000))
                }
                .onEnded { _ in isScrubbing = false }
        )
    }
}

private struct RulerCanvas: View {
    let duration: Double
    let pixelsPerSecond: CGFloat

    var body: some View {
        Canvas { ctx, size in
            let everySec: Double = pixelsPerSecond > 100 ? 1 : (pixelsPerSecond > 40 ? 2 : 5)
            var s: Double = 0
            while s <= duration {
                let x = CGFloat(s) * pixelsPerSecond
                let rect = CGRect(x: x, y: 6, width: 1, height: 10)
                ctx.fill(Path(rect), with: .color(.white.opacity(0.35)))
                let text = Text(timecode(s)).font(Typography.tc).foregroundColor(.white.opacity(0.45))
                ctx.draw(text, at: CGPoint(x: x + 4, y: 8), anchor: .leading)
                s += everySec
            }
        }
    }

    private func timecode(_ s: Double) -> String {
        let total = Int(s)
        let m = total / 60
        let sec = total % 60
        return String(format: "%02d:%02d", m, sec)
    }
}
