import CoreGraphics
import CoreMedia
import Foundation

/// Turns a log of clicks into a track of `ZoomRegion`s — the "magic" of Cursorful.
///
/// Algorithm:
/// 1. Cluster clicks within `clusterWindow` seconds into "gestures."
/// 2. Merge gestures whose **padded time ranges** `[first - leadIn, last + tailOut]` overlap.
///    This yields merged click-lists, so centroids and bounding boxes come from the UNION of
///    all original clicks — N-way-correct (unlike pairwise centroid averaging).
/// 3. Per merged gesture, build a region: zoom-in at `leadIn`, hold, zoom-out at `tailOut`.
/// 4. Clamp to total duration.
///
/// Keyframe times inside a region are **relative to region start**.
enum AutoZoomPlanner {
    struct Settings {
        var clusterWindow: Double = 1.5
        var leadIn: Double = 0.35
        var tailOut: Double = 0.80
        var minHold: Double = 0.40
        var targetScale: CGFloat = 2.0
        var maxScale: CGFloat = 3.0
        var timing: TimingFunction = .cinematic
    }

    static func plan(clicks: [ClickEvent],
                     sourceSize: CGSize,
                     totalDuration: CMTime,
                     settings: Settings = Settings()) -> [ZoomRegion] {

        let downs = clicks.filter { $0.isDown }
        guard !downs.isEmpty else { return [] }

        // 1. Cluster into gestures
        let sorted = downs.sorted(by: { $0.time < $1.time })
        var gestures: [[ClickEvent]] = []
        var current: [ClickEvent] = []
        for click in sorted {
            if let last = current.last,
               click.time.secondsOrZero - last.time.secondsOrZero <= settings.clusterWindow {
                current.append(click)
            } else {
                if !current.isEmpty { gestures.append(current) }
                current = [click]
            }
        }
        if !current.isEmpty { gestures.append(current) }

        // 2. Merge gestures whose padded ranges overlap.
        //    This preserves the underlying click list so centroids use all originals.
        var merged: [[ClickEvent]] = []
        for gesture in gestures {
            guard let last = merged.last else { merged.append(gesture); continue }

            let lastEnd = (last.last!.time.secondsOrZero) + settings.tailOut
            let curStart = (gesture.first!.time.secondsOrZero) - settings.leadIn
            if curStart <= lastEnd {
                merged[merged.count - 1].append(contentsOf: gesture)
            } else {
                merged.append(gesture)
            }
        }

        let safeW = max(1, sourceSize.width)
        let safeH = max(1, sourceSize.height)

        // 3. Build one region per (possibly merged) gesture
        var regions: [ZoomRegion] = merged.map { gesture in
            let positions = gesture.map { $0.position }

            // Centroid over the UNION of clicks — N-way-correct.
            let cx = positions.reduce(CGFloat(0)) { $0 + $1.x } / CGFloat(positions.count)
            let cy = positions.reduce(CGFloat(0)) { $0 + $1.y } / CGFloat(positions.count)

            // Scale: use target for single gestures; for merged spans, widen via the bounding box.
            let scale: CGFloat
            if positions.count == 1 {
                scale = settings.targetScale
            } else {
                let bbox = CGRect.bounding(positions)
                // Fit the bbox into the zoomed viewport with 20% margin.
                let fitScaleX = safeW / max(1, bbox.width) * 0.8
                let fitScaleY = safeH / max(1, bbox.height) * 0.8
                let maxFit = min(fitScaleX, fitScaleY)
                scale = max(1.2, min(settings.maxScale, min(settings.targetScale, maxFit)))
            }

            let centerUV = CGPoint(x: cx / safeW, y: cy / safeH)
            let firstT = gesture.first!.time.secondsOrZero
            let lastT  = gesture.last!.time.secondsOrZero
            let startAbs = max(0, firstT - settings.leadIn)
            let endAbs = max(startAbs + settings.leadIn + settings.minHold + settings.tailOut,
                             lastT + settings.tailOut)
            let dur = endAbs - startAbs

            return ZoomRegion(
                id: UUID(),
                start: CMTime(seconds: startAbs, preferredTimescale: 1_000_000_000),
                end:   CMTime(seconds: endAbs,   preferredTimescale: 1_000_000_000),
                keyframes: buildKeyframes(dur: dur, center: centerUV, scale: scale,
                                          leadIn: settings.leadIn, tailOut: settings.tailOut),
                timingFunction: settings.timing,
                isAutoGenerated: true
            )
        }

        // 4. Clip to total duration
        regions.sort { $0.start < $1.start }
        return regions.compactMap { r in
            var r = r
            if r.start >= totalDuration { return nil }
            if r.end > totalDuration { r.end = totalDuration }
            return r
        }
    }

    /// Build keyframes for a region of duration `dur`, starting at relative time 0.
    private static func buildKeyframes(dur: Double,
                                       center: CGPoint,
                                       scale: CGFloat,
                                       leadIn: Double,
                                       tailOut: Double) -> [ZoomKeyframe] {
        let ts: (Double) -> CMTime = { CMTime(seconds: $0, preferredTimescale: 1_000_000_000) }
        let zoomInEnd = min(leadIn, dur * 0.49)
        let zoomOutStart = max(zoomInEnd + 0.05, dur - tailOut)
        return [
            ZoomKeyframe(time: .zero,            centerUV: center, scale: 1.0),
            ZoomKeyframe(time: ts(zoomInEnd),    centerUV: center, scale: scale),
            ZoomKeyframe(time: ts(zoomOutStart), centerUV: center, scale: scale),
            ZoomKeyframe(time: ts(dur),          centerUV: center, scale: 1.0),
        ]
    }

    /// Evaluate the zoom state at absolute time `t`. Assumes each region has sorted keyframes
    /// (guaranteed by `buildKeyframes` at construction). No redundant sort here.
    static func evaluate(regions: [ZoomRegion], at t: CMTime) -> ZoomSample {
        guard let region = regions.first(where: { t >= $0.start && t <= $0.end }) else {
            return .identity
        }

        let local = CMTimeSubtract(t, region.start)
        let kfs = region.keyframes
        guard let first = kfs.first, let last = kfs.last else { return .identity }

        if local <= first.time {
            return ZoomSample(centerUV: first.centerUV, scale: first.scale)
        }
        if local >= last.time {
            return ZoomSample(centerUV: last.centerUV, scale: last.scale)
        }
        for i in 0..<(kfs.count - 1) {
            let k0 = kfs[i], k1 = kfs[i + 1]
            if local >= k0.time && local <= k1.time {
                let span = k1.time.secondsOrZero - k0.time.secondsOrZero
                let prog = span > 0 ? (local.secondsOrZero - k0.time.secondsOrZero) / span : 1.0
                let u = region.timingFunction.value(at: prog)
                return ZoomSample(
                    centerUV: CGPoint.lerp(k0.centerUV, k1.centerUV, CGFloat(u)),
                    scale:    CGFloat.lerp(k0.scale,    k1.scale,    CGFloat(u))
                )
            }
        }
        return .identity
    }
}
